### ISSUE TITLE
Feedbacks draft

### ISSUE THREAD

**Issue by iamdey** [CaliOpen/Caliopen#255]
## backend

* [x] api/v2 requires Basic Authorization header instead of Bearer #254 
* [x] draft form in a message list is not displayed : the response of /api/v2/identities/locals should give an array (not null)
* [x] participants are missing in discussions/<id> route #279 

## frontend

* [x] a draft creation should not set `type`
* [x] in discussion list the total_count is always 0
* [x] in discussion list use excerpt instead of text propperty
* [x] in main discussion list, date shown are all set to current date, instead of the date_update of the discussion
* [x] into a discussion view (route `/discussions/{discussion_id}`), relative date strings are incorrect. For example, an email received few seconds ago is under a line titled "10 hours ago".
* [x] use actions `set_read` cf. #258 
* [x] detect subrequest to prevent redirect when client is from SSR : in axios client add header for SSR only
* [x] add a route redirect for signout -> to fix in #262 
* [x] http link on tab "Discussions" is `/discussions`, but this path is not handled. -> fix in #262 
* [x] ~~in a message-list buttons reply / copy / delete are not plugged~~ -> #303

**Comment by iamdey** [comment]
cf. #277
