### ISSUE TITLE
TODO frontend & alpha preparations

### ISSUE THREAD

**Issue by iamdey** [CaliOpen/Caliopen#424]
**to ship while the alpha**

* [ ] ignore locale identity in **participant list** (tabs ...) (cf.1)
* [ ] cf. #321 timeout and reload contacts until we got something else than 302 status code
* [ ] refactor draft management using new message_id instead of discussion_id
* [ ] ~~connect local identity for signatures~~ disabled for alpha
* [ ] refactor **electron, cordova**
* [ ] finish the TODO

---

**in progress dey**:

* [x] notif search disabled
* [x] delete a draft from **timeline** and from **a discussion**
* [x] notify draft saved on click save : it's saved, this button comfort you but it is already automatically saved"

---

**in progress myleneb**:

* [x] disable button save and send when draft is not yet touched (or no participants for send)
* [ ] set scroll anchor by tab into store #521 

---

**archives:**

* [x] hide "create account"
* [x] change wording footer : remove mailing-list
* [x] hide account in user menu
* [x] link to https://feedback.caliopen.org/ in footer "or send an email to mailing@alpha-caliopen..." 
* [x] handle error on signup and notify
* [x] hide recover password
* [x] #532
* [x] refresh **timeline** on click discussion
* [x] add message subject if exists in **timeline**
* [x] remove participants when patching **reply** cf. #505 
* [x] check IL header range : -10+10 (cf. X-Caliopen-IL #494) -> PR #499
* [x] display participants in tab label (cf. 1) and remove all requests related to /discussions (which is now deprecated) -> PR #502
* [x] bind message list button reply #525 
* [x] bind message button reply
* [x] feature new contact from scratch #529 
* [x] make sure **err 500** from api are well catched and notify alpha user how to help
* [x] hide 2FA & GPG sections in **user/security** => PR #510
* [x] hide tags management in **settings** => PR #510
* [x] hide remote identities form in **settings/identities** => PR #510
* [x] apply, refactor swipeable actions on timeline & trash discussion list => PR  #508
* [x] hide message list buttons Copy-to
* [x] hide **message** button copy to => PR #498
* [x] create password form in user/security
* [x] bug infinite fetch in message list after compose (I know why) #444 
* [x] bad async load signup
* [x] missing redirect to login
* [x] bad error for notif : always "import error" (err 422)
* [x] catch err 4xx when patching contact
* [x] suggest participant api
* [x] missing mail subject
* [x] add participant UX: tab or focus out should add current value as participant
* [x] ~~fix #452 https://github.com/CaliOpen/Caliopen/compare/fix/frontend/participants-email?expand=1~~
* [x] ~~unexpected PATCH date_insert message : compose > save (redirect) > update (KO)~~ related to #433
* [x] ~~profile is broken~~ outdated via #410 
* [x] ~~birthday is broken~~ outdated via #410

**Comment by myleneb** [comment]
About "refactor swipeable actions on timeline" (= actions displayed on hover/swipe messages in Timeline)
- no more submenu: remove `<DropdownMenu>` and related actions (Archives, Enable Tracking)
- only actions: Delete, Reply, Forward, (Manage Tags?)
poke @iamdey @Lauth0

**Comment by iamdey** [comment]
actions : delete, reply, manage tags (if patch message w/ tags will be ready before alpha)

I don't think we can release forward (aka copy-to)
