### ISSUE TITLE
prepare 0.7.0

### ISSUE THREAD

**Issue by iamdey** [CaliOpen/Caliopen#732]
errors on poc:

* [x] search string then click display more -> err js on hightlights
* [x] change importance level -> err js on filter
* [x] hit «delete» in timeline -> empty black screen. err js in console. API returned a 204 (ok, no content)
* [x] incorrect date shown in timeline for drafts. Field `date` is used by frontend but it is unset until draft is sent.
* [x] API search results on messages provides all messages (eg. 436 instead of 7 for "foo") (OK on preview)
